### ISSUE TITLE
Automatic version bump via Github Actions lacks permissions

### ISSUE THREAD

**Issue by JonathanWenger** [probabilistic-numerics/probnum#293]
The automatic change of the version number triggered by a new release currently is broken since it cannot push to the protected master branch. The following error message is displayed by the Action:

```
> Run ad-m/github-push-action@master
Started: bash /home/runner/work/_actions/ad-m/github-push-action/master/start.sh
Push to branch master
remote: error: GH006: Protected branch update failed for refs/heads/master.        
remote: error: 17 of 17 required status checks are expected. At least 1 approving review is required by reviewers with write access.        
To https://github.com/probabilistic-numerics/probnum.git
 ! [remote rejected] HEAD -> master (protected branch hook declined)
error: failed to push some refs to 'https://github.com/probabilistic-numerics/probnum.git'
Error: Invalid status code: 1
    at ChildProcess.<anonymous> (/home/runner/work/_actions/ad-m/github-push-action/master/start.js:9:19)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5) {
  code: 1
}
Error: Invalid status code: 1
    at ChildProcess.<anonymous> (/home/runner/work/_actions/ad-m/github-push-action/master/start.js:9:19)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
```
This may be fixed by creating a specific Github Token for actions with admin privileges, overriding the required checks on push.

**Comment by JonathanWenger** [comment]
Possibly relevant: https://medium.com/swlh/bump-bump-bump-d0dab616e83

**Comment by JonathanWenger** [comment]
Instead of pushing to master on each release, consider the setup that `black` uses which reads the version number from Github.
