### ISSUE TITLE
ASV benchmarks fail to run

### ISSUE THREAD

**Issue by JonathanWenger** [probabilistic-numerics/probnum#787]
**Describe the bug**
Since the changes to the build setup in #685, the benchmarks fail to run.

**To Reproduce**
Run the following in the command line:

```bash
cd benchmarks
asv check -v
```

Produces:
```
· Discovering benchmarks
·· Uninstalling from virtualenv-py3.8
·· Building 8e9a3db6 <main> for virtualenv-py3.8
·· Error running /home/j/Documents/professional/research/code/probnum/benchmarks/.asv/env/76391772e92136ec87b9940d70226329/bin/python -mpip install setuptools>=61 (exit status 1)
   STDOUT -------->
   
   STDERR -------->
   Traceback (most recent call last):
     File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
       return _run_code(code, main_globals, None,
     File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
       exec(code, run_globals)
     File "/home/j/Documents/professional/research/code/probnum/benchmarks/.asv/env/76391772e92136ec87b9940d70226329/lib/python3.8/site-packages/pip/__main__.py", line 23, in <module>
       from pip._internal.cli.main import main as _main  # isort:skip # noqa
     File "/home/j/Documents/professional/research/code/probnum/benchmarks/.asv/env/76391772e92136ec87b9940d70226329/lib/python3.8/site-packages/pip/_internal/cli/main.py", line 10, in <module>
       from pip._internal.cli.autocompletion import autocomplete
     File "/home/j/Documents/professional/research/code/probnum/benchmarks/.asv/env/76391772e92136ec87b9940d70226329/lib/python3.8/site-packages/pip/_internal/cli/autocompletion.py", line 9, in <module>
       from pip._internal.cli.main_parser import create_main_parser
     File "/home/j/Documents/professional/research/code/probnum/benchmarks/.asv/env/76391772e92136ec87b9940d70226329/lib/python3.8/site-packages/pip/_internal/cli/main_parser.py", line 7, in <module>
       from pip._internal.cli import cmdoptions
     File "/home/j/Documents/professional/research/code/probnum/benchmarks/.asv/env/76391772e92136ec87b9940d70226329/lib/python3.8/site-packages/pip/_internal/cli/cmdoptions.py", line 24, in <module>
       from pip._internal.cli.progress_bars import BAR_TYPES
     File "/home/j/Documents/professional/research/code/probnum/benchmarks/.asv/env/76391772e92136ec87b9940d70226329/lib/python3.8/site-packages/pip/_internal/cli/progress_bars.py", line 7, in <module>
       from pip._internal.utils.compat import WINDOWS
     File "/home/j/Documents/professional/research/code/probnum/benchmarks/.asv/env/76391772e92136ec87b9940d70226329/lib/python3.8/site-packages/pip/_internal/utils/compat.py", line 17, in <module>
       from pip._vendor.six import PY2, text_type
     File "/home/j/Documents/professional/research/code/probnum/benchmarks/.asv/env/76391772e92136ec87b9940d70226329/lib/python3.8/site-packages/pip/_vendor/six.py", line 30, in <module>
       import type
   ModuleNotFoundError: No module named 'type'

·· Failed to build the project and import the benchmark suite.

```

**Expected behavior**
`asv` should discover the existing benchmarks.

**System:**
 - OS: Ubuntu
 - Python 3.8.10 and ProbNum v0.1.22

**Additional context**
Possibly this issue of `asv` has helpful context: https://github.com/airspeed-velocity/asv/issues/903

**Comment by JonathanWenger** [comment]
@marvinpfoertner if you have an idea of what could be the issue here, let me know.

**Comment by marvinpfoertner** [comment]
Since this happens in `six`: Is this related to the Python version?
